### PR TITLE
Issue 37 ajp connector

### PR DESCRIPTION
**Pull request by dsanz**
Hi Zsolt, this should fix liferay#37

I think I'm not able to test this completely (i.e. build a full image). 

Isolatedly, logic works ok. If line comes already uncommented, function does nothing but keep the file contents.

Thanks

### CODE REVIEW

**Comment by zsoltbalogh** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zsoltbalogh** [comment]
@dsanz, for me the tomcat we package into the images listen on *:8009. Could you please double check what was causing the problem for you?

**Comment by zsoltbalogh** [comment]
You have mentioned that you were not been able to build a full image to test. Have you tried the steps here? https://github.com/zsoltbalogh/liferay-docker/blob/readme-back/README.md

**Comment by dsanz** [comment]
Will give this a try. I need to be able to do this to test my soluitions. 
Thanks

**Pull request closed without merging**
